<a href="https://colab.research.google.com/github/frankelikem/ai-course-lab0-/blob/main/colab_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#Lab 0: Colab Practice - Elikem Frank Ameyibor

In [6]:
!nvidia-smi

Fri Jun  5 19:35:37 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [7]:
import numpy as np

In [8]:
matrix = np.ones((5,5))
matrix[1:4, 1:4] = 0
print(matrix)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
np.random.seed(42)
random_data = np.random.randn(100,3)
mean = random_data.mean(axis=0)
std = random_data.std(axis=0) #Standard deviation
normalized_data = (random_data - mean) / std
print(normalized_data.mean(axis=0))
print(normalized_data.std(axis=0))

[-2.60902411e-17  1.55431223e-17 -8.88178420e-18]
[1. 1. 1.]


In [10]:
X = np.random.randn(50, 3)

true_theta = np.array([2.5, -1.2, 3.7])

y = X @ true_theta + np.random.randn(50) * 0.1

X_T = X.T
XTX = X_T @ X
XTX_inv = np.linalg.inv(XTX)
XTy = X_T @ y
theta_hat = XTX_inv @ XTy
print("Estimated coefficients:")
print(theta_hat)

print("\nTrue coefficients:")
print(true_theta)


Estimated coefficients:
[ 2.51723721 -1.19783796  3.72399266]

True coefficients:
[ 2.5 -1.2  3.7]


## Exercise 3 Summary
Task 1

I created a 5×5 NumPy array with border elements set to 1 and interior elements set to 0 using array slicing.

Task 2

I normalized each column of the random dataset by subtracting the column mean and dividing by the column standard deviation. After normalization, each column had a mean approximately equal to 0 and a standard deviation equal to 1.

Task 3

I implemented linear regression using the normal equation. The estimated coefficients (theta_hat) were very close to the true coefficients, showing that the normal equation successfully recovered the underlying relationship in the data.